server {
    listen 80;
    server_name 62.234.18.18;

    location / {
        proxy_pass http://app:8101;

        # 关键：修正 Cookie 的 Domain 和 Path
        proxy_cookie_domain ~.* "";  # 将后端域名或容器名替换为前端 IP

    }
}